/**
 * Generate Grafana provisioning YAML so Prometheus is the default datasource.
 * Written to stackDir/provisioning/datasources when installing Grafana.
 */

export function generateGrafanaDatasourcesYml(): string {
  return `# Generated by Jeeves - Prometheus as default datasource
apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
`;
}
