/**
 * Generate prometheus.yml so Prometheus scrapes all homelab Docker services.
 * Used when installing the prometheus stack; written to ./config/prometheus.yml.
 */

const SCRAPE_INTERVAL = '15s';
const EVAL_INTERVAL = '15s';

/**
 * Returns the full prometheus.yml content.
 * Targets: self, node_exporter (host), cadvisor (all containers), traefik (routing metrics).
 * Traefik is started with --metrics.prometheus=true so /metrics is on the dashboard port (8080).
 * All use Docker network hostnames (proxy network).
 */
export function generatePrometheusYml(): string {
  return `# Generated by Jeeves homelab - scrapes all Dockers (node_exporter, cAdvisor, Traefik)
global:
  scrape_interval: ${SCRAPE_INTERVAL}
  evaluation_interval: ${EVAL_INTERVAL}

scrape_configs:
  # Prometheus self
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Host hardware (CPU, memory, disk, network)
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  # All Docker containers (per-container CPU, memory, network, fs). cAdvisor listens on 8080 inside container (host maps 8081:8080).
  - job_name: 'cadvisor'
    scrape_interval: 60s
    scrape_timeout: 60s
    static_configs:
      - targets: ['cadvisor:8080']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'container_(network_tcp_usage_total|network_udp_usage_total|network_fd_usage)'
        action: drop

  # Traefik (routing metrics; enabled via --metrics.prometheus=true on traefik)
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
`;
}
